"""FSI Phase 7: Deterministic Financial Reasoning Research Report
(docs/fre_runs/fsi_phase7_preregistration.md).

A pure PRESENTATION layer -- one function,
`render_report(snapshot: CompanyMemory360) -> str`, that turns an
already-built Phase 6 `CompanyMemory360` snapshot into a structured,
human-readable Markdown document. This module introduces NO new
reasoning, inference, scoring, ranking, summarization, health
assessment, or investment interpretation of any kind. Every sentence it
emits is a direct, mechanical substitution of a field that already
exists in `financial_reasoning_conclusions`, `extracted_facts`, or
`CompanyMemory` -- nothing is computed, nothing is derived, nothing is
generated by inference. No LLM call exists anywhere in this module.

Ordering discipline (docs/fre_runs/fsi_phase7_preregistration.md
requirement 8: "never reorder evidence to imply importance unless that
ordering already exists in the source data"): corporate-memory lists
(filings, dividends, corporate actions, events) are rendered in the
EXACT order `company_memory.py` already returns them in (chronological
by filing/announced date -- that ordering already exists in the source
query, so it is preserved, not re-derived). Financial-reasoning
conclusions (ratios/trends/flags) have no inherent order of their own
(they are independent, unordered facts about a company), so this module
imposes exactly one neutral, disclosed, non-importance-based order:
alphabetical by `metric`, then chronological by `period_end` -- never by
value, by whether a flag fired, or by any other criterion that could
read as an editorial judgment.

Missing-data discipline (requirement 7: "never hide missing data --
report it explicitly"): every `insufficient_data` conclusion is
rendered with its own `limitations` text explaining what's missing,
in the same list as `computed` conclusions, never filtered out or
moved to a footnote. Every `NULL` confidence_tier is rendered as an
explicit "confidence tier not recorded" phrase, never silently omitted
or presented as equivalent to a real tier.
"""
from __future__ import annotations

from ngxrot.fre.company_memory_360 import CompanyMemory360
from ngxrot.fre.pit_financial_memory import KnowableConclusion

_CONFIDENCE_TIER_LABELS = {
    "direct_reported": "direct_reported (literally stated in the source filing)",
    "mapped_equivalent": "mapped_equivalent (derived from a differently-labeled but "
                          "structurally equivalent filing line)",
    "derived": "derived (computed from other reported figures via a disclosed formula)",
    "interpretation": "interpretation",
}
_NULL_CONFIDENCE_LABEL = (
    "confidence tier NOT RECORDED -- this fact predates the confidence_tier "
    "column introduced in FSI Phase 2 and was never backfilled; treat as "
    "UNKNOWN confidence, not as equivalent to a recorded tier"
)


def _format_confidence_tier(tier: str | None) -> str:
    if tier is None:
        return _NULL_CONFIDENCE_LABEL
    return _CONFIDENCE_TIER_LABELS.get(tier, tier)


def _format_value(value_numeric: float | None, value_text: str | None) -> str:
    parts = []
    if value_numeric is not None:
        parts.append(f"{value_numeric:.6f}")
    if value_text is not None:
        parts.append(value_text)
    return " / ".join(parts) if parts else "(no value -- see status below)"


def _render_source_facts(conclusion: KnowableConclusion) -> list[str]:
    lines = []
    if not conclusion.source_facts:
        lines.append("  - Source facts: none (see limitations above for why)")
        return lines
    lines.append("  - Source facts:")
    for sf in conclusion.source_facts:
        lines.append(
            f"    - fact_id={sf.fact_id} ({sf.role}): {sf.fact_type}, "
            f"doc_id={sf.doc_id}, filed {sf.filing_date}"
        )
    return lines


def _render_conclusion(conclusion: KnowableConclusion) -> list[str]:
    lines = [
        f"### {conclusion.metric} ({conclusion.period_start or 'n/a'} to "
        f"{conclusion.period_end or 'n/a'})",
        f"- Status: {conclusion.status}",
        f"- Value: {_format_value(conclusion.value_numeric, conclusion.value_text)}",
        f"- Confidence tier: {_format_confidence_tier(conclusion.confidence_tier)}",
        f"- Method: {conclusion.method}",
        f"- Limitations: {conclusion.limitations}",
        f"- Knowable as of: {conclusion.knowable_as_of}",
    ]
    lines.extend(_render_source_facts(conclusion))
    lines.append("")
    return lines


def _sorted_conclusions(conclusions: list[KnowableConclusion]) -> list[KnowableConclusion]:
    """The one neutral, disclosed order this module ever imposes: alphabetical
    by metric, then chronological by period_end. Never by value, status, or
    whether a flag fired -- see module docstring."""
    return sorted(conclusions, key=lambda c: (c.metric, c.period_end or ""))


def _render_conclusion_section(title: str, conclusion_type: str,
                                conclusions: list[KnowableConclusion]) -> list[str]:
    lines = [f"## {title}", ""]
    matching = _sorted_conclusions([c for c in conclusions if c.conclusion_type == conclusion_type])
    if not matching:
        lines.append(f"No {title.lower()} conclusions are knowable as of this date.")
        lines.append("")
        return lines
    for c in matching:
        lines.extend(_render_conclusion(c))
    return lines


def render_report(snapshot: CompanyMemory360) -> str:
    """Pure, deterministic: identical input always produces identical
    output. No randomness, no wall-clock timestamp, no LLM call."""
    lines: list[str] = []
    lines.append(f"# Financial Reasoning Research Report — {snapshot.ticker}")
    lines.append("")
    lines.append(f"**As of:** {snapshot.as_of_date}")
    lines.append("")
    lines.append(
        "*This is a deterministic, template-generated report. It contains no "
        "inference, no LLM-generated text, no valuation, no ranking, no health "
        "score, and no investment recommendation. Every statement below is a "
        "direct restatement of a field already stored in the underlying "
        "database, per docs/fre_runs/fsi_phase7_preregistration.md.*"
    )
    lines.append("")

    # --- Corporate memory (FRE-3), preserved in its own existing order -------
    corp = snapshot.corporate
    lines.append("## Filing History")
    lines.append("")
    if not corp.filing_history:
        lines.append("No filings found as of this date.")
    else:
        for f in corp.filing_history:
            lines.append(
                f"- doc_id={f.doc_id} | {f.doc_type} | filed {f.filing_date} | "
                f"source_confidence={f.source_confidence}"
            )
    lines.append("")

    lines.append("## Dividend History")
    lines.append("")
    if not corp.dividend_history:
        lines.append("No dividend facts found as of this date.")
    else:
        for d in corp.dividend_history:
            value_part = f", value={d.numeric_value}" if d.numeric_value is not None else ""
            lines.append(f"- fact_id={d.fact_id} | filed {d.filing_date} | {d.description}{value_part}")
    lines.append("")

    lines.append("## Corporate Action History")
    lines.append("")
    if not corp.corporate_action_history:
        lines.append("No corporate-action facts found as of this date.")
    else:
        for a in corp.corporate_action_history:
            value_part = f", value={a.numeric_value}" if a.numeric_value is not None else ""
            lines.append(f"- fact_id={a.fact_id} | {a.fact_type} | filed {a.filing_date} | "
                         f"{a.description}{value_part}")
    lines.append("")

    lines.append("## Management History")
    lines.append("")
    if not corp.management_history:
        lines.append("No management lineage data available.")
    else:
        for m in corp.management_history:
            lines.append(f"- {m}")
    lines.append("")

    lines.append("## Major Event History")
    lines.append("")
    if not corp.major_event_history:
        lines.append("No ticker-scoped event data available.")
    else:
        for e in corp.major_event_history:
            lines.append(f"- {e}")
    lines.append("")

    lines.append("## Corporate Memory Coverage Notes")
    lines.append("")
    for note in corp.coverage_note:
        lines.append(f"- {note}")
    lines.append(f"- {corp.excluded_blocked_facts} fact(s) excluded from dividend/corporate-action "
                 f"history above for being blocked_by_self_critique (counted, not silently dropped).")
    lines.append("")

    # --- Financial reasoning conclusions (FSI Phase 3, via Phase 4's PIT gate) --
    fin = snapshot.financial
    lines.append("---")
    lines.append("")
    all_conclusions = fin.conclusions
    lines.extend(_render_conclusion_section("Ratios", "ratio", all_conclusions))
    lines.extend(_render_conclusion_section("Trends", "trend", all_conclusions))
    lines.extend(_render_conclusion_section("Flags", "flag", all_conclusions))

    lines.append("## Financial Reasoning Coverage Notes")
    lines.append("")
    lines.append(f"- {len(fin.conclusions)} financial-reasoning conclusion(s) knowable as of "
                 f"{snapshot.as_of_date}.")
    lines.append(f"- {fin.excluded_count} conclusion(s) exist for this ticker in total but are NOT "
                 f"yet knowable as of this date (a later filing has not yet been made public) -- "
                 f"excluded from this report, not fabricated.")
    computed_count = sum(1 for c in fin.conclusions if c.status == "computed")
    insufficient_count = sum(1 for c in fin.conclusions if c.status == "insufficient_data")
    lines.append(f"- Of the conclusions shown above: {computed_count} computed, "
                 f"{insufficient_count} insufficient_data (explicitly reported, not hidden).")
    lines.append("")

    return "\n".join(lines)
